### ISSUE TITLE
docker base image "arch-devel" is missing

### ISSUE THREAD

**Issue by mgrossmann** [daniel64/lspf#7]
I'm unable to use docker to build LSPF.
The base image used in the Dockerfile, "arch-devel", is missing.

**Comment by ehrt74** [comment]
in case you're still trying to build this, i got the docker build running by making these changes:

    FROM archlinux
    LABEL maintainer="rvjansen@xs4all.nl"
    RUN yes | pacman -Syu
    RUN yes | pacman -S svn gcc git make cmake boost ncurses
    WORKDIR /

**Comment by daniel64** [comment]
Added in latest lspf update.
