### ISSUE TITLE
Remap newline and enter keys. 

### ISSUE THREAD

**Issue by daveyc** [daniel64/lspf#8]
To make this more usable I suggest an option to remap the ENTER key to NEWLINE and right-CNTL to ENTER to emulate 3270 terminals. This is a critical feature for most ISPF users.

**Comment by daniel64** [comment]
Indeed that would be nice, but unfortunately in ncurses right-CNTL does not produce any input - it only modifies other keys.  Remapping ENTER is easy but what do you then use so simulate ENTER?

I'll close for now, but if you find a solution, let me know and I'll try to implement it.

Regards,  Daniel
