### ISSUE TITLE
lspf.h missing ZSPROF

### ISSUE THREAD

**Issue by cto741** [daniel64/lspf#9]
ZSPROF is not set and does not exist in src/lspf.h.  
The closest is ZUPROF in spelling is this the correct name?

**Comment by daniel64** [comment]
My mistake.  ZSPROF was removed some time ago from lspf.h but I didn't update the INSTALL instructions.  Will do on the next update to lspf.  Just make sure other paths in lspf.h exist and everything should be okay.  Let me know if you have other problems.
